### ISSUE TITLE
Incorrect thousands separator

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [devj3ns/monopoly-banking#5]
Hi @devj3ns, awesome project ✨ 😍 

In the demo I saw that you are using `.` for the thousands separator, however, that is probably not the correct one for the locale on the device.

The `intl` package provides ways to do this properly.
See this function for example: https://github.com/simpleclub/math_keyboard/blob/491120508a9b665182dcc7e674323ae26bcc3f2e/math_keyboard/lib/src/widgets/decimal_separator.dart#L12  
It uses the `intl` package to determine the decimal separator and you can use the same method to determine the thousands separator. I think that would be `GROUP_SEP` (https://pub.dev/documentation/intl/latest/number_symbols/NumberSymbols/GROUP_SEP.html).

However, I think the best way is to use [`NumberFormat`](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html) directly instead of doing it manually because that uses the correct number format based on the locale by default.  
Maybe you are already doing that, but it seems like it is not properly formatted.

**Or**, I was tricked by the device locale being `de` while you are using English strings :D (also possible). In that case, I would force the locale :)

**Comment by devj3ns** [comment]
Hey @creativecreatorormaybenot,
thanks a lot for creating an issue.

It's a good point you are making. I will take a look at the resources you linked and work on it in the next few days.
